### ISSUE TITLE
Hand off checklist

### ISSUE THREAD

**Issue by apmcguigan** [CS-4820-Library-Project/COUNTER-5-Report-Tool#92]
**Github:**
- [x] Delete old branches

**General:**
- [x] Set Fetch Reports to default page, using setCurrentIndex
- [x] Finalize requirements.txt
- [x] Test Mac & Linux compatibility 
- [x] Create .exe files for all 3 OSes

 **Create documents for:**
- [x] How to make executable
- [x] Dev quickstart guides: How to make UI, How to install project. 

 **Legal:**
- [x] Pick Open Source License Type
- [x] Sign legal document

 **Gitea:**
- [x] Move wiki pages over to Gitea
- [x] Push codebase to Gitea
- [x] Make Gitea public
- [x] Name, Contact Info, Sections worked on
